openapi: 3.0.3
info:
  title: AUTHENTICATION Rest API
  description: REST API endpoints for managing Holidays
  version: 0.1.x-SNAPSHOT
servers:
  - url: 'https'
  - url: 'http'
paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create a new user
      description: Create a new user
      operationId: createUser
      requestBody:
        description: User object that need to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthDTO'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
        403:
          description: P2002 | P2005

components:
  schemas:
    AuthDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        lastName:
          type: string
        firstName:
          type: string
        gender:
          type: string
        email:
          type: string
        password:
          type: string










