openapi: 3.0.3
info:
  title: HOLIDAYS Rest API
  description: REST API endpoints for managing Holidays
  version: 0.1.x-SNAPSHOT
servers:
  - url: 'https'
  - url: 'http'
paths:
  /:
    get:
      tags:
        - Holiday
      summary: Fetch Holidays
      description: Fetch Holidays
      operationId: getAllHolidays
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HolidayDTO'
  /{id}:
    get:
      tags:
        - Holiday
      summary: Fetch a Holiday by id
      description: Fetch a Holiday by id
      operationId: getHolidayById
      parameters:
        - name: id
          description: the holiday's id to get
          in: path
          required: true
          schema:
            type: integer
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HolidayDTO'
    post:
      tags:
        - Holiday
      summary: create an a holiday
      description: create an existing User
      operationId: createHoliday
      parameters:
      requestBody:
        description: Holiday object that need to be edit
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HolidayDTO'
      responses:
        204:
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: uuid
    delete:
      tags:
        - Holiday
      summary: delete an existing User
      description: delete an existing User
      operationId: deleteHoliday
      parameters:
        - name: id
          description: the holiday's id to delete
          in: path
          required: true
          schema:
            type: integer
            format: uuid
      responses:
        204:
          description: Successful operation        
components:
  schemas:
    HolidayDTO:
      type: object
      properties:
        id:
          type: integer
          description: identifier the holiday
        type:
          type: string
          description: type of the holiday
        startingDate:
          type: string
          format: date
          description: the startingDate of the holiday
        endingDate:
          type: string
          format: date
          description: the endingDate of the holiday
        returnDate:
          type: string
          format: date
          description: the code of the speciality
        description:
          type: string
          description: the description of the holiday
        numberOfDays:
          type: integer
          description: the number of days of the holiday
        createdAt:
          type: string
          format: date
          description: the date of the holiday creation






